CREATE TABLE USUARIO(
NDOC VARCHAR(20) PRIMARY KEY,
TIPODOC VARCHAR(4) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
NOME VARCHAR(30),
DATANASC DATE,
RG VARCHAR(16),
RAZAOSOCIAL VARCHAR(30)
);

CREATE TABLE ANALISTA(
CPF VARCHAR(16) PRIMARY KEY,
NOME VARCHAR(20) NOT NULL
);

CREATE TABLE GERENTE(
CPF VARCHAR (16) PRIMARY KEY,
NOME VARCHAR(20) NOT NULL
);

CREATE TABLE C(
CPF VARCHAR(16) PRIMARY KEY,
CARGO VARCHAR(16) NOT NULL
);

CREATE TABLE RECURSOHUMANO(
NOMEPROFISSAO VARCHAR(16) PRIMARY KEY,
DESCRICAO TEXT
);

CREATE TABLE TIPORECURSOFISICO(
IDTIPORECURSO VARCHAR(16) PRIMARY KEY,
DESCRICAO TEXT,
NOME VARCHAR(20) NOT NULL
);

CREATE TABLE ARMAZEM(
IDARMAZEM VARCHAR(16) PRIMARY KEY,
ENDERECO VARCHAR (50) NOT NULL, 
CAPACIDADEMAX DOUBLE PRECISION NOT NULL,
CONSTRAINT CK_CAPACIDADE CHECK (CAPACIDADEMAX>0)
);

CREATE TABLE PEDIDO(
IDPEDIDO VARCHAR(16) PRIMARY KEY,
NOMEEVENTOPROPOSTO VARCHAR(32),
STATUS VARCHAR(16) NOT NULL DEFAULT 'Em Análise',
LOCALPROPOSTO VARCHAR(50),
DATAINICIOPROPOSTO DATE,
DATAFIMPROPOSTO DATE,
DATASUBMISSAO DATE,
DESCRICAO TEXT,
USUARIO VARCHAR(20) NOT NULL,
ANALISTA VARCHAR(16) NOT NULL,
GERENTE VARCHAR(16) NOT NULL,
CONSTRAINT FK_PEDIDO FOREIGN KEY (USUARIO) REFERENCES USUARIO(NDOC) ON DELETE CASCADE,
CONSTRAINT FK_PEDIDO2 FOREIGN KEY (ANALISTA) REFERENCES ANALISTA(CPF) ON DELETE SET NULL,
CONSTRAINT FK_PEDIDO3 FOREIGN KEY (GERENTE) REFERENCES GERENTE(CPF) ON DELETE SET NULL
);

CREATE TABLE EVENTO(
NOMEEVENTOEFETIVO VARCHAR(32) NOT NULL,
DATAINICIOEFETIVO DATE NOT NULL,
DATAFIMEVENTO DATE NOT NULL,
STATUSDEFINITIVO VARCHAR(16) NOT NULL,
LOCALEFETIVO VARCHAR(50) NOT NULL,
PEDIDO VARCHAR(16) NOT NULL,
CONSTRAINT PK_EVENTO PRIMARY KEY (NOMEEVENTOEFETIVO, DATAINICIOEFETIVO),
CONSTRAINT FK_EVENTO FOREIGN KEY (PEDIDO) REFERENCES PEDIDO(IDPEDIDO) ON DELETE CASCADE,
UNIQUE (PEDIDO)
);

CREATE TABLE DOCUMENTODEREQUISITO(
PEDIDO VARCHAR(16) NOT NULL,
STATUS VARCHAR(16) DEFAULT 'Pendente',
CONSTRAINT PK_DOCUMENTO PRIMARY KEY (PEDIDO),
CONSTRAINT FK_DOCUMENTO FOREIGN KEY(PEDIDO) REFERENCES PEDIDO(IDPEDIDO) ON DELETE CASCADE
);

CREATE TABLE PROPOSTA(
DATA DATE NOT NULL,
USUARIO VARCHAR(20) NOT NULL,
ANALISTA VARCHAR(16) NOT NULL,
DESCRICAOPROPOSTA TEXT NOT NULL,
CONSTRAINT PK_PROPOSTA PRIMARY KEY (DATA, USUARIO, ANALISTA),
CONSTRAINT FK_PROPOSTA FOREIGN KEY (ANALISTA) REFERENCES ANALISTA(CPF) ON DELETE SET NULL,
CONSTRAINT FK_PROPOSTA2 FOREIGN KEY (USUARIO) REFERENCES USUARIO(NDOC) ON DELETE CASCADE
);

CREATE TABLE DOC_RH(
DOCUMENTODEREQUISITO VARCHAR(16) NOT NULL,
RECURSOHUMANO VARCHAR(16) NOT NULL,
QUANTIDADE INTEGER NOT NULL,
CONSTRAINT PK_DOC_RH PRIMARY KEY (DOCUMENTODEREQUISITO, RECURSOHUMANO),
CONSTRAINT FK_DOC_RH FOREIGN KEY (DOCUMENTODEREQUISITO) REFERENCES DOCUMENTODEREQUISITO(PEDIDO) ON DELETE CASCADE,
CONSTRAINT FK_DOC_RH2 FOREIGN KEY (RECURSOHUMANO) REFERENCES RECURSOHUMANO(NOMEPROFISSAO) ON DELETE CASCADE,
CONSTRAINT CK_QUANTIDADE CHECK (QUANTIDADE>0)
);

CREATE TABLE DOC_TIPORECURSO(
DOCUMENTODEREQUISITO VARCHAR(16) NOT NULL,
TIPORECURSOFISICO VARCHAR(16) NOT NULL,
QUANTIDADE INTEGER NOT NULL,
CONSTRAINT PK_DOC_TIPORECURSO PRIMARY KEY (DOCUMENTODEREQUISITO, TIPORECURSOFISICO),
CONSTRAINT FK_DOC_TIPORECURSO FOREIGN KEY (DOCUMENTODEREQUISITO) REFERENCES DOCUMENTODEREQUISITO(PEDIDO) ON DELETE CASCADE,
CONSTRAINT FK_DOC_TIPORECURSO2 FOREIGN KEY (TIPORECURSOFISICO) REFERENCES TIPORECURSOFISICO(IDTIPORECURSO) ON DELETE CASCADE,
CONSTRAINT CH_QUANTIDADE CHECK (QUANTIDADE>0)
);

CREATE TABLE ITEM(
NROPATRIMONIO VARCHAR(16) PRIMARY KEY,
STATUSITEM VARCHAR(16) DEFAULT 'Disponível',
QUALIDADE VARCHAR(16),
TAMANHO DOUBLE PRECISION NOT NULL,
TIPORECURSOFISICO VARCHAR(16) NOT NULL,
ARMAZEM VARCHAR(16),
CONSTRAINT FK_ITEM FOREIGN KEY (TIPORECURSOFISICO) REFERENCES TIPORECURSOFISICO(IDTIPORECURSO) ON DELETE CASCADE,
CONSTRAINT FK_ITEM2 FOREIGN KEY (ARMAZEM) REFERENCES ARMAZEM(IDARMAZEM) ON DELETE SET NULL,
CONSTRAINT CK_TAMANHO CHECK (TAMANHO>0)
);


CREATE TABLE ALOCA (
EVENTONOME varchar(32) NOT NULL,
EVENTODATA DATE NOT NULL,
ITEM VARCHAR (16) NOT NULL,
DIAENTRADA DATE NOT NULL,
DIASAIDA DATE NOT NULL,
CONSTRAINT PK_ALOCA PRIMARY KEY (EVENTONOME, EVENTODATA, ITEM),
CONSTRAINT FK_ALOCA_EVENTO FOREIGN KEY(EVENTONOME, EVENTODATA) REFERENCES EVENTO(NOMEEVENTOEFETIVO, DATAINICIOEFETIVO) ON DELETE RESTRICT,
CONSTRAINT FK_ALOCA_ITEM FOREIGN KEY(ITEM) REFERENCES ITEM(NROPATRIMONIO)
);



