CREATE TABLE USUARIO(
NDOC VARCHAR(16) PRIMARY KEY,
TIPODOC VARCHAR(4) NOT NULL,
EMAIL VARCHAR(20) NOT NULL,
NOME VARCHAR(20),
DATANASC DATE,
RG VARCHAR(16),
RAZAOSOCIAL VARCHAR(20)
);

CREATE TABLE ANALISTA(
CPF VARCHAR(16) PRIMARY KEY,
NOME VARCHAR(20) NOT NULL
);

CREATE TABLE GERENTE(
CPF VARCHAR (16) PRIMARY KEY,
NOME VARCHAR(20) NOT NULL
);

CREATE TABLE C(
CPF VARCHAR(16) PRIMARY KEY,
CARGO VARCHAR(16) NOT NULL
);

CREATE TABLE RECURSOHUMANO(
NOMEPROFISSAO VARCHAR(16) PRIMARY KEY,
DESCRICAO TEXT
);

CREATE TABLE TIPORECURSOFISICO(
IDTIPORECURSO VARCHAR(16) PRIMARY KEY,
DESCRICAO TEXT,
NOME VARCHAR(20) NOT NULL
);

CREATE TABLE ARMAZEM(
IDARMAZEM VARCHAR(16) PRIMARY KEY,
ENDERECO VARCHAR (30) NOT NULL, 
CAPACIDADEMAX DOUBLE PRECISION NOT NULL
);

CREATE TABLE PEDIDO(
IDPEDIDO VARCHAR(16) PRIMARY KEY,
NOMEEVENTOPROPOSTO VARCHAR(32),
STATUS VARCHAR(16) NOT NULL,
LOCALPROPOSTO VARCHAR(32),
DATAINICIOPROPOSTO DATE,
DATAFIMPROPOSTO DATE,
DATASUBMISSAO DATE,
DESCRICAO TEXT,
USUARIO VARCHAR(16) NOT NULL,
ANALISTA VARCHAR(16) NOT NULL,
GERENTE VARCHAR(16) NOT NULL,
CONSTRAINT FK_PEDIDO FOREIGN KEY (USUARIO) REFERENCES USUARIO(NDOC),
CONSTRAINT FK_PEDIDO2 FOREIGN KEY (ANALISTA) REFERENCES ANALISTA(CPF),
CONSTRAINT FK_PEDIDO3 FOREIGN KEY (GERENTE) REFERENCES GERENTE(CPF)
);

CREATE TABLE EVENTO(
NOMEEVENTOEFETIVO VARCHAR(32) NOT NULL,
DATAINICIOEFETIVO DATE NOT NULL,
DATAFIMEVENTO DATE NOT NULL,
STATUSDEFINITIVO VARCHAR(16) NOT NULL,
LOCALEFETIVO VARCHAR(32) NOT NULL,
PEDIDO VARCHAR(16) NOT NULL,
CONSTRAINT PK_EVENTO PRIMARY KEY (NOMEEVENTOEFETIVO, DATAINICIOEFETIVO),
CONSTRAINT FK_EVENTO FOREIGN KEY (PEDIDO) REFERENCES PEDIDO(IDPEDIDO),
UNIQUE (PEDIDO)
);

CREATE TABLE DOCUMENTODEREQUISITO(
PEDIDO VARCHAR(16) NOT NULL,
STATUS VARCHAR(16),
CONSTRAINT PK_DOCUMENTO PRIMARY KEY (PEDIDO),
CONSTRAINT FK_DOCUMENTO FOREIGN KEY(PEDIDO) REFERENCES PEDIDO(IDPEDIDO)
);

CREATE TABLE PROPOSTA(
DATA DATE NOT NULL,
USUARIO VARCHAR(16) NOT NULL,
ANALISTA VARCHAR(16) NOT NULL,
DESCRICAOPROPOSTA TEXT NOT NULL,
CONSTRAINT PK_PROPOSTA PRIMARY KEY (DATA, USUARIO, ANALISTA),
CONSTRAINT FK_PROPOSTA FOREIGN KEY (ANALISTA) REFERENCES ANALISTA(CPF),
CONSTRAINT FK_PROPOSTA2 FOREIGN KEY (USUARIO) REFERENCES USUARIO(NDOC)
);

CREATE TABLE DOC_RH(
DOCUMENTODEREQUISITO VARCHAR(16) NOT NULL,
RECURSOHUMANO VARCHAR(16) NOT NULL,
QUANTIDADE INTEGER NOT NULL,
CONSTRAINT PK_DOC_RH PRIMARY KEY (DOCUMENTODEREQUISITO, RECURSOHUMANO),
CONSTRAINT FK_DOC_RH FOREIGN KEY (DOCUMENTODEREQUISITO) REFERENCES DOCUMENTODEREQUISITO(PEDIDO),
CONSTRAINT FK_DOC_RH2 FOREIGN KEY (RECURSOHUMANO) REFERENCES RECURSOHUMANO(NOMEPROFISSAO)
);

CREATE TABLE DOC_TIPORECURSO(
DOCUMENTODEREQUISITO VARCHAR(16) NOT NULL,
TIPORECURSOFISICO VARCHAR(16) NOT NULL,
QUANTIDADE INTEGER NOT NULL,
CONSTRAINT PK_DOC_TIPORECURSO PRIMARY KEY (DOCUMENTODEREQUISITO, TIPORECURSOFISICO),
CONSTRAINT FK_DOC_TIPORECURSO FOREIGN KEY (DOCUMENTODEREQUISITO) REFERENCES DOCUMENTODEREQUISITO(PEDIDO),
CONSTRAINT FK_DOC_TIPORECURSO2 FOREIGN KEY (TIPORECURSOFISICO) REFERENCES TIPORECURSOFISICO(IDTIPORECURSO)
);

CREATE TABLE ITEM(
NROPATRIMONIO VARCHAR(16) PRIMARY KEY,
STATUSITEM VARCHAR(16),
QUALIDADE VARCHAR(16),
TAMANHO DOUBLE PRECISION NOT NULL,
TIPORECURSOFISICO VARCHAR(16) NOT NULL,
ARMAZEM VARCHAR(16),
CONSTRAINT FK_ITEM FOREIGN KEY (TIPORECURSOFISICO) REFERENCES TIPORECURSOFISICO(IDTIPORECURSO),
CONSTRAINT FK_ITEM2 FOREIGN KEY (ARMAZEM) REFERENCES ARMAZEM(IDARMAZEM)
);


CREATE TABLE ALOCA (
EVENTONOME varchar(32) NOT NULL,
EVENTODATA DATE NOT NULL,
ITEM VARCHAR (16) NOT NULL,
DIAENTRADA DATE NOT NULL,
DIASAIDA DATE NOT NULL,
CONSTRAINT PK_ALOCA PRIMARY KEY (EVENTONOME, EVENTODATA, ITEM),
CONSTRAINT FK_ALOCA_EVENTO FOREIGN KEY(EVENTONOME) REFERENCES EVENTO(NOMEEVENTOEFETIVO),
CONSTRAINT FK_ALOCA_EVENTODATA FOREIGN KEY(EVENTODATA) REFERENCES EVENTO(DATAINICIOEFETIVO),
CONSTRAINT FK_ALOCA_ITEM FOREIGN KEY(ITEM) REFERENCES ITEM(NROPATRIMONIO)
);



